import io
import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env so skipif conditions (SUPABASE_URL, OPENAI_API_KEY) are visible at
# collection time, before any backend module is imported.
load_dotenv(Path(__file__).parent.parent / ".env")

# PyTorch MPS (Apple Silicon) doesn't support float64; fall back to CPU for
# ops that require it. Must be set before torch is imported.
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")

import pytest
from fpdf import FPDF


@pytest.fixture(scope="session")
def sample_pdf_path(tmp_path_factory) -> Path:
    """Tiny 2-page PDF with a text section and a simple table, generated by fpdf2."""
    pdf = FPDF()

    # Page 1 — prose section
    pdf.add_page()
    pdf.set_font("Helvetica", size=16)
    pdf.cell(0, 10, "Introduction", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=11)
    pdf.multi_cell(
        0,
        8,
        (
            "This paper presents a novel approach to information retrieval using "
            "large language models combined with hybrid search over vector databases. "
            "We demonstrate that combining dense and sparse retrieval improves "
            "recall by 15% on standard benchmarks."
        ),
    )

    # Page 2 — simple table (formatted as text; DocLing will treat it as a table)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", size=12)
    pdf.cell(0, 10, "Results", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", size=10)
    for row in [
        ("Method", "Precision", "Recall"),
        ("BM25", "0.71", "0.68"),
        ("Dense", "0.74", "0.72"),
        ("Hybrid", "0.81", "0.83"),
    ]:
        pdf.cell(60, 8, row[0], border=1)
        pdf.cell(40, 8, row[1], border=1)
        pdf.cell(40, 8, row[2], border=1, new_x="LMARGIN", new_y="NEXT")

    tmp = tmp_path_factory.mktemp("fixtures") / "sample.pdf"
    pdf.output(str(tmp))
    return tmp


@pytest.fixture(scope="session")
def sample_pdf_bytes(sample_pdf_path: Path) -> bytes:
    return sample_pdf_path.read_bytes()
